"""Write requirements.lock: every runtime dependency of requirements.txt, pinned.

requirements.txt lists the packages the app uses directly, with version
ranges. requirements.lock pins the whole dependency closure to the versions
installed and tested; setup.bat and CI install from it. The closure is
computed from the installed packages' metadata (Requires-Dist, with the
environment markers evaluated for this Python), never from pip freeze, which
would also pick up unrelated packages of a shared Python.

Refresh (Python 3.14 on Windows, from the install folder):
  1. python -m pip install --upgrade --upgrade-strategy eager -r requirements.txt
  2. python -m unittest discover -s tests -t . -v
  3. python tools\\lock_requirements.py
  4. Commit requirements.lock with the change. CI installs exactly the lock,
     runs pip check and "python tools\\lock_requirements.py --check".

Writing fails (exit 1, nothing written) when a package of the closure is not
installed, or an installed version is outside a range: requirements.txt's for
the packages listed there, or a requirer's Requires-Dist for its dependency.

--check writes nothing and exits 1 when any of these holds:
  - writing would fail as above;
  - a pin in requirements.lock is outside requirements.txt's range for that
    package or outside the range an installed requirer's Requires-Dist gives
    for it, or a package the closure needs has no pin (with the lock
    installed, as in CI, the requirers' metadata is that of the pinned
    versions);
  - requirements.lock is not exactly what writing would produce from the
    installed packages (a pin missing, extra or at another version; a diff is
    printed).
Only these ranges and markers are checked, as found in requirements.txt and
the installed metadata; nothing is looked up on PyPI, so --check does not
tell whether newer versions exist.
Standard library only: it needs no package besides the ones it inspects.
"""
import argparse
import difflib
import importlib.metadata
import os
import platform
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REQUIREMENTS_TXT = os.path.join(REPO_ROOT, "requirements.txt")
REQUIREMENTS_LOCK = os.path.join(REPO_ROOT, "requirements.lock")
SUPPORTED = ("win32", (3, 14))
HEADER = (
    "# Generated by tools/lock_requirements.py from requirements.txt. Do not edit.",
    "# Every runtime dependency, pinned to the version installed and tested with",
    "# Python 3.14 on Windows. setup.bat and CI install from this file.",
)

_NAME_RE = re.compile(r"\s*([A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?)\s*(?:\[([^\]]*)\])?")
_CLAUSE_RE = re.compile(r"\s*(===|==|!=|<=|>=|~=|<|>)\s*([0-9A-Za-z*][0-9A-Za-z.*+!_-]*)\s*")
_LOCK_LINE_RE = re.compile(r"([A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?)==(\S+)")
_TOKEN_RE = re.compile(r"""\s*(?:('[^']*'|"[^"]*")|(===|==|!=|<=|>=|~=|<|>)|([()])|([A-Za-z_][A-Za-z0-9_.]*))""")
_RELEASE_RE = re.compile(r"[0-9]+(?:\.[0-9]+)*")
_MARKER_VARIABLES = {
    "implementation_name", "implementation_version", "os_name", "platform_machine",
    "platform_python_implementation", "platform_release", "platform_system", "platform_version",
    "python_full_version", "python_version", "sys_platform", "extra",
}


def canonical_name(name):
    """PEP 503 normalized name (also used for extras)."""
    return re.sub(r"[-_.]+", "-", name).lower()


def current_environment():
    """Marker values of the running interpreter, as pip evaluates them."""
    info = sys.implementation.version
    implementation_version = f"{info.major}.{info.minor}.{info.micro}"
    if info.releaselevel != "final":
        implementation_version += info.releaselevel[0] + str(info.serial)
    return {
        "implementation_name": sys.implementation.name,
        "implementation_version": implementation_version,
        "os_name": os.name,
        "platform_machine": platform.machine(),
        "platform_python_implementation": platform.python_implementation(),
        "platform_release": platform.release(),
        "platform_system": platform.system(),
        "platform_version": platform.version(),
        "python_full_version": platform.python_version(),
        "python_version": ".".join(platform.python_version_tuple()[:2]),
        "sys_platform": sys.platform,
    }


def parse_requirement(text):
    """(canonical name, set of canonical extras, version clauses, marker text)
    of a PEP 508 requirement. Clauses are a tuple of (operator, version), e.g.
    ((">=", "2.57"), ("<", "3")); URL requirements are refused."""
    requirement, _sep, marker = text.partition(";")
    match = _NAME_RE.match(requirement)
    if not match:
        raise ValueError(f"cannot parse requirement: {text!r}")
    extras = {canonical_name(extra.strip()) for extra in (match.group(2) or "").split(",") if extra.strip()}
    specifier = requirement[match.end():].strip()
    if specifier.startswith("@"):
        raise ValueError(f"URL requirements are not supported: {text!r}")
    if specifier.startswith("(") and specifier.endswith(")"):
        specifier = specifier[1:-1]
    clauses = []
    for part in specifier.split(",") if specifier.strip() else []:
        clause = _CLAUSE_RE.fullmatch(part)
        if not clause:
            raise ValueError(f"cannot parse version specifier {part.strip()!r} in {text!r}")
        clauses.append(clause.groups())
    return canonical_name(match.group(1)), extras, tuple(clauses), marker.strip()


def specifier_text(clauses):
    return ",".join(op + version for op, version in clauses)


def satisfies(version, clauses):
    """True when version meets every clause. Only release versions (digits and
    dots) are ordered; anything else raises ValueError instead of guessing."""
    return all(_compare(version, op, wanted, None) for op, wanted in clauses)


def _release(text):
    return tuple(int(part) for part in text.split(".")) if _RELEASE_RE.fullmatch(text) else None


def _compare(left, op, right, variable):
    if op in ("in", "not in"):
        return (left in right) == (op == "in")
    if variable == "extra":
        left, right = canonical_name(left), canonical_name(right)
    if op == "===":
        return left == right
    if op in ("==", "!=") and right.endswith(".*") and _release(left) and _release(right[:-2]):
        prefix = _release(right[:-2])
        return (_release(left)[:len(prefix)] == prefix) == (op == "==")
    a, b = _release(left), _release(right)
    if a is None or b is None:
        if op in ("==", "!="):
            return (left == right) == (op == "==")
        raise ValueError(f"cannot compare {left!r} {op} {right!r} as versions")
    width = max(len(a), len(b))
    a, b = a + (0,) * (width - len(a)), b + (0,) * (width - len(b))
    if op == "~=":
        size = len(_release(right))
        if size < 2:
            raise ValueError(f"~= needs at least two release numbers: {right!r}")
        return a >= b and a[:size - 1] == b[:size - 1]
    return {"==": a == b, "!=": a != b, "<": a < b, "<=": a <= b, ">": a > b, ">=": a >= b}[op]


def evaluate_marker(marker, environment):
    """PEP 508 environment marker -> bool. Raises ValueError on anything it
    does not understand instead of guessing."""
    tokens, pos = [], 0
    while pos < len(marker):
        match = _TOKEN_RE.match(marker, pos)
        if not match or match.end() == pos:
            if marker[pos:].strip():
                raise ValueError(f"cannot parse marker: {marker!r}")
            break
        pos = match.end()
        string, op, paren, word = match.groups()
        tokens.append(("str", string[1:-1]) if string else ("op", op or paren or word))
    tokens.append(("end", None))
    index = 0

    def take(expected=None):
        nonlocal index
        token = tokens[index]
        if expected is not None and token != ("op", expected):
            raise ValueError(f"expected {expected!r} in marker: {marker!r}")
        index += 1
        return token

    def value():
        kind, text = take()
        if kind == "str":
            return text, None
        if kind == "op" and text in _MARKER_VARIABLES:
            if text not in environment:
                raise ValueError(f"no value for marker variable {text!r}")
            return environment[text], text
        raise ValueError(f"unexpected {text!r} in marker: {marker!r}")

    def comparison():
        if tokens[index] == ("op", "("):
            take("(")
            result = either()
            take(")")
            return result
        left, left_var = value()
        kind, op = take()
        if (kind, op) == ("op", "not"):
            take("in")
            op = "not in"
        elif kind != "op" or op not in ("===", "==", "!=", "<=", ">=", "~=", "<", ">", "in"):
            raise ValueError(f"expected a comparison in marker: {marker!r}")
        right, right_var = value()
        return _compare(left, op, right, left_var or right_var)

    def both():
        result = comparison()
        while tokens[index] == ("op", "and"):
            take()
            right = comparison()  # evaluated anyway, so every part is checked
            result = result and right
        return result

    def either():
        result = both()
        while tokens[index] == ("op", "or"):
            take()
            right = both()
            result = result or right
        return result

    result = either()
    if tokens[index][0] != "end":
        raise ValueError(f"unexpected {tokens[index][1]!r} in marker: {marker!r}")
    return result


def read_requirements(path):
    """[parse_requirement tuples] of a plain requirements file (no pip options)."""
    requirements = []
    with open(path, encoding="utf-8") as handle:
        for raw in handle:
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            if line.startswith("-"):
                raise ValueError(f"pip options are not supported in {path}: {line}")
            requirements.append(parse_requirement(line))
    return requirements


def installed_distribution(name):
    """(version, Requires-Dist lines) of an installed package."""
    try:
        distribution = importlib.metadata.distribution(name)
    except importlib.metadata.PackageNotFoundError:
        raise LookupError(
            f"{name} is not installed; run: python -m pip install -r requirements.txt"
        ) from None
    return distribution.version, distribution.requires or []


def resolve_closure(top_level, environment, distribution):
    """(versions, edges) for top_level (read_requirements tuples) and
    everything they require in `environment`, including what requested extras
    add. versions: {canonical name: version}; edges: {(requirer, name,
    clauses)}, the requirer being "requirements.txt" or "<name> <version>".
    distribution(name) -> (version, Requires-Dist lines), e.g.
    installed_distribution."""
    requested = {}
    versions = {}
    edges = set()
    pending = []
    for name, extras, clauses, marker in top_level:
        if not marker or evaluate_marker(marker, dict(environment, extra="")):
            edges.add(("requirements.txt", name, clauses))
            pending.append((name, extras))
    while pending:
        name, extras = pending.pop()
        known = requested.get(name)
        if known is not None and extras <= known:
            continue
        requested[name] = (known or set()) | extras
        version, requires = distribution(name)
        versions[name] = version
        for text in requires:
            dependency, dependency_extras, clauses, marker = parse_requirement(text)
            if not marker or any(
                evaluate_marker(marker, dict(environment, extra=extra)) for extra in {""} | requested[name]
            ):
                edges.add((f"{name} {version}", dependency, clauses))
                pending.append((dependency, dependency_extras))
    return versions, edges


def unsatisfied(edges, versions, where):
    """One message per edge whose package is missing from `versions` or whose
    version there is outside the requirer's range. `where` says what
    `versions` are: "installed" or "pinned in requirements.lock"."""
    problems = []
    for requirer, name, clauses in sorted(edges):
        wanted = f"{name}{specifier_text(clauses)}"
        if name not in versions:
            problems.append(f"{requirer} requires {wanted}, but {name} is not {where}")
        elif not satisfies(versions[name], clauses):
            problems.append(f"{requirer} requires {wanted}, but {name} {versions[name]} is {where}")
    return problems


def parse_lock(text):
    """{canonical name: version} of requirements.lock text."""
    pins = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        match = _LOCK_LINE_RE.fullmatch(line)
        if not match:
            raise ValueError(f"requirements.lock line is not name==version: {line!r}")
        pins[canonical_name(match.group(1))] = match.group(2)
    return pins


def render_lock(versions):
    return "\n".join([*HEADER, *(f"{name}=={versions[name]}" for name in sorted(versions))]) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description="Write requirements.lock from requirements.txt.")
    parser.add_argument("--check", action="store_true", help="only compare requirements.lock; write nothing")
    args = parser.parse_args(argv)
    if (sys.platform, sys.version_info[:2]) != SUPPORTED:
        print("error: run this with Python 3.14 on Windows, the supported environment", file=sys.stderr)
        return 2
    try:
        versions, edges = resolve_closure(
            read_requirements(REQUIREMENTS_TXT), current_environment(), installed_distribution
        )
        problems = unsatisfied(edges, versions, "installed")
    except (LookupError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    text = render_lock(versions)
    if not args.check:
        if problems:
            for problem in problems:
                print(f"error: {problem}", file=sys.stderr)
            print("error: requirements.lock was not written", file=sys.stderr)
            return 1
        with open(REQUIREMENTS_LOCK, "w", encoding="ascii", newline="\n") as handle:
            handle.write(text)
        print(f"wrote {REQUIREMENTS_LOCK}")
        return 0
    try:
        with open(REQUIREMENTS_LOCK, encoding="ascii") as handle:
            current = handle.read()
    except FileNotFoundError:
        current = ""
    try:
        problems += unsatisfied(edges, parse_lock(current), "pinned in requirements.lock")
    except ValueError as exc:
        problems.append(str(exc))
    if current != text:
        sys.stdout.writelines(difflib.unified_diff(
            current.splitlines(keepends=True), text.splitlines(keepends=True),
            "requirements.lock", "closure of requirements.txt (installed)",
        ))
        problems.append("requirements.lock is not the dependency closure of requirements.txt (installed)")
    if problems:
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        return 1
    print("requirements.lock matches the installed dependency closure of requirements.txt, within every range")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
